### ISSUE TITLE
Fehler beim Laden der Daten vom BfS-Server

### ISSUE THREAD

**Issue by Nunmalfix** [crycode-de/ioBroker.odl#100]
Ich bekomme beim Installieren auf der Konfig-Seite nur die Fehlermeldung:
Fehler beim Laden der Daten vom BfS-Server: TypeError: Failed to fetch

Eingaben sind nicht möglich - auch die vorher gesuchte Messstellen ID wird nicht übernommen.
Speicher bzw. Speicher und Schließen bleibt ausgegraut.

**Comment by Nunmalfix** [comment]
Im Browser geht es - aber mit curl auf dem iobroker host kommt das:
 curl https://www.imis.bfs.de/ogc/opendata/ows?service=WFS&version=1.1.0&request=GetFeature&typeName=opendata:odlinfo_odl_1h_latest&outputFormat=application/json
[1] 2219189
[2] 2219190
[3] 2219191
[4] 2219192
[2]   Fertig                  version=1.1.0
[3]-  Fertig                  request=GetFeature
stefan@uhomesrv:~$ <?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 https://www.imis.bfs.de/ogc/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="MissingParameterValue" locator="request">
<ows:ExceptionText>Could not determine geoserver request from http request org.geoserver.monitor.MonitorServletRequest@163be5d7</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>

**Comment by crycode-de** [comment]
Bei dem curl Aufruf muss die URL in Anführungszeichen gesetzt werden, da diese ein &-Zeichen enthält.

Gibt es denn in der Browserkonsole eine Fehlermeldung, wenn du die Adapterkonfiguration öffnest? Da sollte eigentlich stehen, warum das nicht geladen werden konnte.

**Comment by crycode-de** [comment]
Interessant, dass der Ad-Blocker diese Anfrage geblockt hat.
Ich werde bei Gelegenheit dann mal die Fehlermeldung um einen Hinweis dazu ergänzen.
