### ISSUE TITLE
Warnmeldungen

### ISSUE THREAD

**Issue by weindler** [crycode-de/ioBroker.odl#102]
Hi, folgende Warnmeldungen bekomme ich seit ein paar Tagen bei jedem Aufruf, kannst du damit etwas anfangen.

`<html><body>

odl.0 | 2023-09-17 08:30:13.696 | warn | Got no data for latest layer
-- | -- | -- | --
odl.0 | 2023-09-17 08:30:13.696 | warn | Error: unable to verify the first certificate
odl.0 | 2023-09-17 08:30:13.694 | warn | Error loading latest data from server!

</body>
</html>`

Die Abfrage scheint aber zu funktionieren da sich die Zahlen ändern.

**Comment by 63chris** [comment]
bei mir exakt das selbe

**Comment by rimhaeuser** [comment]
seit dem 19.09.2023 auch bei mir

**Comment by crycode-de** [comment]
Die Datenschnittstelle vom BfS nutzt seit kurzem scheinbar ein neues SSL-Zertifikat, welches wohl nicht immer vollständig validiert werden kann.

Ich habe den gleichen Fehler...

Bin dran. 👍

**Comment by weindler** [comment]
> Die Datenschnittstelle vom BfS nutzt seit kurzem scheinbar ein neues SSL-Zertifikat, welches wohl nicht immer vollständig validiert werden kann.
> 
> Ich habe den gleichen Fehler...
> 
> Bin dran. 👍

Danke dir, Keinen Streß @crycode-de

**Comment by rimhaeuser** [comment]
Was fehlt ist der Parameter "rejectUnauthorized: false" in der Webadresse

`...kenn:051220003#&sortBy=end_measure+A&maxFeatures=168',%20method:%20'GET',%20"rejectUnauthorized":%20false,...`

das müßte man nur im Adapter einpflegen. Scheinbar wurde das bis zum 13.09. nicht benötigt.

Siehe hierzu auch [https://forum.iobroker.net/topic/68377/odl-adapter/10?_=1694957070325](https://forum.iobroker.net/topic/68377/odl-adapter/10?_=1694957070325)

**Comment by crycode-de** [comment]
@rimhaeuser Nein, der Parameter fehlt **nicht**! Der würde die Zertifikatsprüfung deaktivieren und damit quasi einen Sicherheitsmechanismus aushebeln.
Das Problem muss beim BfS gelöst werden. Das werde ich morgen in die Wege leiten.

**Comment by rimhaeuser** [comment]
@crycode-de Herzlichen Dank für die Info. Und herzlichen Dank für deine Arbeit.

**Comment by crycode-de** [comment]
@Haifeif Denke ich habe alles was ich brauche, danke! :)

**Comment by crycode-de** [comment]
Jetzt sollte es wohl wieder gehen.
Bei mir sind zumindest die Warnungen weg und die Daten kommen wieder.
Könnt ihr das bestätigen?

**Comment by weindler** [comment]
Jepp, kann ich bestätigen, keine Warnmeldungen mehr und Daten sind aktuell, danke @crycode-de, top Job.

**Comment by 63chris** [comment]
jep, alles wieder gut, vielen Dank

**Comment by crycode-de** [comment]
Dann schließe ich hier mal.
Danke auch an euch fürs Melden und Testen!

Sollten wieder Probleme auftreten, dann bitte einfach einen neuen Issue erstellen, oder mich im ioBroker Forum direkt erwähnen, damit ich das mitbekomme.

**Comment by Haifeif** [comment]
Alles gut!

Tolle Leistung, da bin ich manchmal andere Wartezeiten gewöhnt!

LG Uwe
